version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_redis_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gmp_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    build:
      context: .
      dockerfile: ./compose/production/redis/Dockerfile
    image: gmp_production_redis
    container_name: redis
    volumes:
      - local_redis_data:/data:Z
    env_file:
      - ./.envs/.local/.redis
    ports:
      - "6379:6379"
