# Generated by Django 3.1.13 on 2021-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBSFree1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('views', models.BigIntegerField(default=0)),
                ('recommended_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=16)),
                ('author_ip', models.GenericIPAddressField()),
                ('title', models.CharField(max_length=128)),
                ('main_text', models.CharField(max_length=65536)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
